#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-codec
Version  : 1.2
Release  : 1
URL      : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
Source0  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
Source1  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
Source2  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom
Source3  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
Source4  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.11/commons-codec-1.11.pom
Source5  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.2/commons-codec-1.2.pom
Source6  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.3/commons-codec-1.3.jar
Source7  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.3/commons-codec-1.3.pom
Source8  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
Source9  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
Source10  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
Source11  : https://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.1
Requires: mvn-commons-codec-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-codec package.
Group: Data

%description data
data components for the mvn-commons-codec package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.11
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.11

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.11
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.11

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.3
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.3
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.6
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.6
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.9
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.9
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/commons-codec/commons-codec/1.9


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.pom
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.pom
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.pom
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.pom
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
/usr/share/java/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.pom
